apiVersion: apps/v1
kind: Deployment
metadata:
  name: g11n-middleware
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: g11n-middleware
  template:
    metadata:
      labels:
        app: g11n-middleware
    spec:
      containers:
        - name: g11n-middleware
          image: uhub.service.ucloud.cn/entropypool/g11n-middleware:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/G11nMiddleware
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: g11n-middleware-config
            items:
              - key: service-conf
                path: G11nMiddleware.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: g11n-middleware
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50600
      targetPort: 50600
    - name: grpc
      port: 50601
      targetPort: 50601
    - name: healthz
      port: 50602
      targetPort: 50602
    - name: prometheus
      port: 50603
      targetPort: 50603
  selector:
    app: g11n-middleware
