// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/appcountry"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/applang"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/country"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/lang"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/message"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/schema"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appcountryMixin := schema.AppCountry{}.Mixin()
	appcountry.Policy = privacy.NewPolicies(appcountryMixin[0], schema.AppCountry{})
	appcountry.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := appcountry.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	appcountryMixinFields0 := appcountryMixin[0].Fields()
	_ = appcountryMixinFields0
	appcountryFields := schema.AppCountry{}.Fields()
	_ = appcountryFields
	// appcountryDescCreatedAt is the schema descriptor for created_at field.
	appcountryDescCreatedAt := appcountryMixinFields0[0].Descriptor()
	// appcountry.DefaultCreatedAt holds the default value on creation for the created_at field.
	appcountry.DefaultCreatedAt = appcountryDescCreatedAt.Default.(func() uint32)
	// appcountryDescUpdatedAt is the schema descriptor for updated_at field.
	appcountryDescUpdatedAt := appcountryMixinFields0[1].Descriptor()
	// appcountry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appcountry.DefaultUpdatedAt = appcountryDescUpdatedAt.Default.(func() uint32)
	// appcountry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appcountry.UpdateDefaultUpdatedAt = appcountryDescUpdatedAt.UpdateDefault.(func() uint32)
	// appcountryDescDeletedAt is the schema descriptor for deleted_at field.
	appcountryDescDeletedAt := appcountryMixinFields0[2].Descriptor()
	// appcountry.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	appcountry.DefaultDeletedAt = appcountryDescDeletedAt.Default.(func() uint32)
	// appcountryDescAppID is the schema descriptor for app_id field.
	appcountryDescAppID := appcountryFields[1].Descriptor()
	// appcountry.DefaultAppID holds the default value on creation for the app_id field.
	appcountry.DefaultAppID = appcountryDescAppID.Default.(func() uuid.UUID)
	// appcountryDescCountryID is the schema descriptor for country_id field.
	appcountryDescCountryID := appcountryFields[2].Descriptor()
	// appcountry.DefaultCountryID holds the default value on creation for the country_id field.
	appcountry.DefaultCountryID = appcountryDescCountryID.Default.(func() uuid.UUID)
	// appcountryDescID is the schema descriptor for id field.
	appcountryDescID := appcountryFields[0].Descriptor()
	// appcountry.DefaultID holds the default value on creation for the id field.
	appcountry.DefaultID = appcountryDescID.Default.(func() uuid.UUID)
	applangMixin := schema.AppLang{}.Mixin()
	applang.Policy = privacy.NewPolicies(applangMixin[0], schema.AppLang{})
	applang.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := applang.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	applangMixinFields0 := applangMixin[0].Fields()
	_ = applangMixinFields0
	applangFields := schema.AppLang{}.Fields()
	_ = applangFields
	// applangDescCreatedAt is the schema descriptor for created_at field.
	applangDescCreatedAt := applangMixinFields0[0].Descriptor()
	// applang.DefaultCreatedAt holds the default value on creation for the created_at field.
	applang.DefaultCreatedAt = applangDescCreatedAt.Default.(func() uint32)
	// applangDescUpdatedAt is the schema descriptor for updated_at field.
	applangDescUpdatedAt := applangMixinFields0[1].Descriptor()
	// applang.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	applang.DefaultUpdatedAt = applangDescUpdatedAt.Default.(func() uint32)
	// applang.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	applang.UpdateDefaultUpdatedAt = applangDescUpdatedAt.UpdateDefault.(func() uint32)
	// applangDescDeletedAt is the schema descriptor for deleted_at field.
	applangDescDeletedAt := applangMixinFields0[2].Descriptor()
	// applang.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	applang.DefaultDeletedAt = applangDescDeletedAt.Default.(func() uint32)
	// applangDescAppID is the schema descriptor for app_id field.
	applangDescAppID := applangFields[1].Descriptor()
	// applang.DefaultAppID holds the default value on creation for the app_id field.
	applang.DefaultAppID = applangDescAppID.Default.(func() uuid.UUID)
	// applangDescLangID is the schema descriptor for lang_id field.
	applangDescLangID := applangFields[2].Descriptor()
	// applang.DefaultLangID holds the default value on creation for the lang_id field.
	applang.DefaultLangID = applangDescLangID.Default.(func() uuid.UUID)
	// applangDescMain is the schema descriptor for main field.
	applangDescMain := applangFields[3].Descriptor()
	// applang.DefaultMain holds the default value on creation for the main field.
	applang.DefaultMain = applangDescMain.Default.(bool)
	// applangDescID is the schema descriptor for id field.
	applangDescID := applangFields[0].Descriptor()
	// applang.DefaultID holds the default value on creation for the id field.
	applang.DefaultID = applangDescID.Default.(func() uuid.UUID)
	countryMixin := schema.Country{}.Mixin()
	country.Policy = privacy.NewPolicies(countryMixin[0], schema.Country{})
	country.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := country.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	countryMixinFields0 := countryMixin[0].Fields()
	_ = countryMixinFields0
	countryFields := schema.Country{}.Fields()
	_ = countryFields
	// countryDescCreatedAt is the schema descriptor for created_at field.
	countryDescCreatedAt := countryMixinFields0[0].Descriptor()
	// country.DefaultCreatedAt holds the default value on creation for the created_at field.
	country.DefaultCreatedAt = countryDescCreatedAt.Default.(func() uint32)
	// countryDescUpdatedAt is the schema descriptor for updated_at field.
	countryDescUpdatedAt := countryMixinFields0[1].Descriptor()
	// country.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	country.DefaultUpdatedAt = countryDescUpdatedAt.Default.(func() uint32)
	// country.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	country.UpdateDefaultUpdatedAt = countryDescUpdatedAt.UpdateDefault.(func() uint32)
	// countryDescDeletedAt is the schema descriptor for deleted_at field.
	countryDescDeletedAt := countryMixinFields0[2].Descriptor()
	// country.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	country.DefaultDeletedAt = countryDescDeletedAt.Default.(func() uint32)
	// countryDescCountry is the schema descriptor for country field.
	countryDescCountry := countryFields[1].Descriptor()
	// country.DefaultCountry holds the default value on creation for the country field.
	country.DefaultCountry = countryDescCountry.Default.(string)
	// countryDescFlag is the schema descriptor for flag field.
	countryDescFlag := countryFields[2].Descriptor()
	// country.DefaultFlag holds the default value on creation for the flag field.
	country.DefaultFlag = countryDescFlag.Default.(string)
	// countryDescCode is the schema descriptor for code field.
	countryDescCode := countryFields[3].Descriptor()
	// country.DefaultCode holds the default value on creation for the code field.
	country.DefaultCode = countryDescCode.Default.(string)
	// countryDescShort is the schema descriptor for short field.
	countryDescShort := countryFields[4].Descriptor()
	// country.DefaultShort holds the default value on creation for the short field.
	country.DefaultShort = countryDescShort.Default.(string)
	// countryDescID is the schema descriptor for id field.
	countryDescID := countryFields[0].Descriptor()
	// country.DefaultID holds the default value on creation for the id field.
	country.DefaultID = countryDescID.Default.(func() uuid.UUID)
	langMixin := schema.Lang{}.Mixin()
	lang.Policy = privacy.NewPolicies(langMixin[0], schema.Lang{})
	lang.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := lang.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	langMixinFields0 := langMixin[0].Fields()
	_ = langMixinFields0
	langFields := schema.Lang{}.Fields()
	_ = langFields
	// langDescCreatedAt is the schema descriptor for created_at field.
	langDescCreatedAt := langMixinFields0[0].Descriptor()
	// lang.DefaultCreatedAt holds the default value on creation for the created_at field.
	lang.DefaultCreatedAt = langDescCreatedAt.Default.(func() uint32)
	// langDescUpdatedAt is the schema descriptor for updated_at field.
	langDescUpdatedAt := langMixinFields0[1].Descriptor()
	// lang.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	lang.DefaultUpdatedAt = langDescUpdatedAt.Default.(func() uint32)
	// lang.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	lang.UpdateDefaultUpdatedAt = langDescUpdatedAt.UpdateDefault.(func() uint32)
	// langDescDeletedAt is the schema descriptor for deleted_at field.
	langDescDeletedAt := langMixinFields0[2].Descriptor()
	// lang.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	lang.DefaultDeletedAt = langDescDeletedAt.Default.(func() uint32)
	// langDescLang is the schema descriptor for lang field.
	langDescLang := langFields[1].Descriptor()
	// lang.DefaultLang holds the default value on creation for the lang field.
	lang.DefaultLang = langDescLang.Default.(string)
	// langDescLogo is the schema descriptor for logo field.
	langDescLogo := langFields[2].Descriptor()
	// lang.DefaultLogo holds the default value on creation for the logo field.
	lang.DefaultLogo = langDescLogo.Default.(string)
	// langDescName is the schema descriptor for name field.
	langDescName := langFields[3].Descriptor()
	// lang.DefaultName holds the default value on creation for the name field.
	lang.DefaultName = langDescName.Default.(string)
	// langDescShort is the schema descriptor for short field.
	langDescShort := langFields[4].Descriptor()
	// lang.DefaultShort holds the default value on creation for the short field.
	lang.DefaultShort = langDescShort.Default.(string)
	// langDescID is the schema descriptor for id field.
	langDescID := langFields[0].Descriptor()
	// lang.DefaultID holds the default value on creation for the id field.
	lang.DefaultID = langDescID.Default.(func() uuid.UUID)
	messageMixin := schema.Message{}.Mixin()
	message.Policy = privacy.NewPolicies(messageMixin[0], schema.Message{})
	message.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := message.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	messageMixinFields0 := messageMixin[0].Fields()
	_ = messageMixinFields0
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageMixinFields0[0].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() uint32)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageMixinFields0[1].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() uint32)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() uint32)
	// messageDescDeletedAt is the schema descriptor for deleted_at field.
	messageDescDeletedAt := messageMixinFields0[2].Descriptor()
	// message.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	message.DefaultDeletedAt = messageDescDeletedAt.Default.(func() uint32)
	// messageDescAppID is the schema descriptor for app_id field.
	messageDescAppID := messageFields[1].Descriptor()
	// message.DefaultAppID holds the default value on creation for the app_id field.
	message.DefaultAppID = messageDescAppID.Default.(func() uuid.UUID)
	// messageDescLangID is the schema descriptor for lang_id field.
	messageDescLangID := messageFields[2].Descriptor()
	// message.DefaultLangID holds the default value on creation for the lang_id field.
	message.DefaultLangID = messageDescLangID.Default.(func() uuid.UUID)
	// messageDescMessageID is the schema descriptor for message_id field.
	messageDescMessageID := messageFields[3].Descriptor()
	// message.DefaultMessageID holds the default value on creation for the message_id field.
	message.DefaultMessageID = messageDescMessageID.Default.(string)
	// messageDescMessage is the schema descriptor for message field.
	messageDescMessage := messageFields[4].Descriptor()
	// message.DefaultMessage holds the default value on creation for the message field.
	message.DefaultMessage = messageDescMessage.Default.(string)
	// messageDescGetIndex is the schema descriptor for get_index field.
	messageDescGetIndex := messageFields[5].Descriptor()
	// message.DefaultGetIndex holds the default value on creation for the get_index field.
	message.DefaultGetIndex = messageDescGetIndex.Default.(uint32)
	// messageDescDisabled is the schema descriptor for disabled field.
	messageDescDisabled := messageFields[6].Descriptor()
	// message.DefaultDisabled holds the default value on creation for the disabled field.
	message.DefaultDisabled = messageDescDisabled.Default.(bool)
	// messageDescShort is the schema descriptor for short field.
	messageDescShort := messageFields[7].Descriptor()
	// message.DefaultShort holds the default value on creation for the short field.
	message.DefaultShort = messageDescShort.Default.(string)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.11.2" // Version of ent codegen.
)
