// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/appcountry"
	"github.com/google/uuid"
)

// AppCountry is the model entity for the AppCountry schema.
type AppCountry struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// CountryID holds the value of the "country_id" field.
	CountryID uuid.UUID `json:"country_id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppCountry) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case appcountry.FieldCreatedAt, appcountry.FieldUpdatedAt, appcountry.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case appcountry.FieldID, appcountry.FieldAppID, appcountry.FieldCountryID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AppCountry", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppCountry fields.
func (ac *AppCountry) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case appcountry.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ac.ID = *value
			}
		case appcountry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ac.CreatedAt = uint32(value.Int64)
			}
		case appcountry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ac.UpdatedAt = uint32(value.Int64)
			}
		case appcountry.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ac.DeletedAt = uint32(value.Int64)
			}
		case appcountry.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				ac.AppID = *value
			}
		case appcountry.FieldCountryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field country_id", values[i])
			} else if value != nil {
				ac.CountryID = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this AppCountry.
// Note that you need to call AppCountry.Unwrap() before calling this method if this AppCountry
// was returned from a transaction, and the transaction was committed or rolled back.
func (ac *AppCountry) Update() *AppCountryUpdateOne {
	return (&AppCountryClient{config: ac.config}).UpdateOne(ac)
}

// Unwrap unwraps the AppCountry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ac *AppCountry) Unwrap() *AppCountry {
	_tx, ok := ac.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppCountry is not a transactional entity")
	}
	ac.config.driver = _tx.drv
	return ac
}

// String implements the fmt.Stringer.
func (ac *AppCountry) String() string {
	var builder strings.Builder
	builder.WriteString("AppCountry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ac.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", ac.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", ac.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", ac.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", ac.AppID))
	builder.WriteString(", ")
	builder.WriteString("country_id=")
	builder.WriteString(fmt.Sprintf("%v", ac.CountryID))
	builder.WriteByte(')')
	return builder.String()
}

// AppCountries is a parsable slice of AppCountry.
type AppCountries []*AppCountry

func (ac AppCountries) config(cfg config) {
	for _i := range ac {
		ac[_i].config = cfg
	}
}
