// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/applang"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/predicate"
)

// AppLangQuery is the builder for querying AppLang entities.
type AppLangQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AppLang
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppLangQuery builder.
func (alq *AppLangQuery) Where(ps ...predicate.AppLang) *AppLangQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit adds a limit step to the query.
func (alq *AppLangQuery) Limit(limit int) *AppLangQuery {
	alq.limit = &limit
	return alq
}

// Offset adds an offset step to the query.
func (alq *AppLangQuery) Offset(offset int) *AppLangQuery {
	alq.offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *AppLangQuery) Unique(unique bool) *AppLangQuery {
	alq.unique = &unique
	return alq
}

// Order adds an order step to the query.
func (alq *AppLangQuery) Order(o ...OrderFunc) *AppLangQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// First returns the first AppLang entity from the query.
// Returns a *NotFoundError when no AppLang was found.
func (alq *AppLangQuery) First(ctx context.Context) (*AppLang, error) {
	nodes, err := alq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{applang.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *AppLangQuery) FirstX(ctx context.Context) *AppLang {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AppLang ID from the query.
// Returns a *NotFoundError when no AppLang ID was found.
func (alq *AppLangQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = alq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{applang.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *AppLangQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AppLang entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AppLang entity is found.
// Returns a *NotFoundError when no AppLang entities are found.
func (alq *AppLangQuery) Only(ctx context.Context) (*AppLang, error) {
	nodes, err := alq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{applang.Label}
	default:
		return nil, &NotSingularError{applang.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *AppLangQuery) OnlyX(ctx context.Context) *AppLang {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AppLang ID in the query.
// Returns a *NotSingularError when more than one AppLang ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *AppLangQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = alq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{applang.Label}
	default:
		err = &NotSingularError{applang.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *AppLangQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AppLangs.
func (alq *AppLangQuery) All(ctx context.Context) ([]*AppLang, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return alq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (alq *AppLangQuery) AllX(ctx context.Context) []*AppLang {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AppLang IDs.
func (alq *AppLangQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := alq.Select(applang.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *AppLangQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *AppLangQuery) Count(ctx context.Context) (int, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return alq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (alq *AppLangQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *AppLangQuery) Exist(ctx context.Context) (bool, error) {
	if err := alq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return alq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *AppLangQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppLangQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *AppLangQuery) Clone() *AppLangQuery {
	if alq == nil {
		return nil
	}
	return &AppLangQuery{
		config:     alq.config,
		limit:      alq.limit,
		offset:     alq.offset,
		order:      append([]OrderFunc{}, alq.order...),
		predicates: append([]predicate.AppLang{}, alq.predicates...),
		// clone intermediate query.
		sql:    alq.sql.Clone(),
		path:   alq.path,
		unique: alq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AppLang.Query().
//		GroupBy(applang.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (alq *AppLangQuery) GroupBy(field string, fields ...string) *AppLangGroupBy {
	grbuild := &AppLangGroupBy{config: alq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return alq.sqlQuery(ctx), nil
	}
	grbuild.label = applang.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.AppLang.Query().
//		Select(applang.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (alq *AppLangQuery) Select(fields ...string) *AppLangSelect {
	alq.fields = append(alq.fields, fields...)
	selbuild := &AppLangSelect{AppLangQuery: alq}
	selbuild.label = applang.Label
	selbuild.flds, selbuild.scan = &alq.fields, selbuild.Scan
	return selbuild
}

func (alq *AppLangQuery) prepareQuery(ctx context.Context) error {
	for _, f := range alq.fields {
		if !applang.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	if applang.Policy == nil {
		return errors.New("ent: uninitialized applang.Policy (forgotten import ent/runtime?)")
	}
	if err := applang.Policy.EvalQuery(ctx, alq); err != nil {
		return err
	}
	return nil
}

func (alq *AppLangQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AppLang, error) {
	var (
		nodes = []*AppLang{}
		_spec = alq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*AppLang).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &AppLang{config: alq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(alq.modifiers) > 0 {
		_spec.Modifiers = alq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (alq *AppLangQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	if len(alq.modifiers) > 0 {
		_spec.Modifiers = alq.modifiers
	}
	_spec.Node.Columns = alq.fields
	if len(alq.fields) > 0 {
		_spec.Unique = alq.unique != nil && *alq.unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *AppLangQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := alq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (alq *AppLangQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   applang.Table,
			Columns: applang.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: applang.FieldID,
			},
		},
		From:   alq.sql,
		Unique: true,
	}
	if unique := alq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := alq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applang.FieldID)
		for i := range fields {
			if fields[i] != applang.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *AppLangQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(applang.Table)
	columns := alq.fields
	if len(columns) == 0 {
		columns = applang.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.unique != nil && *alq.unique {
		selector.Distinct()
	}
	for _, m := range alq.modifiers {
		m(selector)
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (alq *AppLangQuery) ForUpdate(opts ...sql.LockOption) *AppLangQuery {
	if alq.driver.Dialect() == dialect.Postgres {
		alq.Unique(false)
	}
	alq.modifiers = append(alq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return alq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (alq *AppLangQuery) ForShare(opts ...sql.LockOption) *AppLangQuery {
	if alq.driver.Dialect() == dialect.Postgres {
		alq.Unique(false)
	}
	alq.modifiers = append(alq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return alq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (alq *AppLangQuery) Modify(modifiers ...func(s *sql.Selector)) *AppLangSelect {
	alq.modifiers = append(alq.modifiers, modifiers...)
	return alq.Select()
}

// AppLangGroupBy is the group-by builder for AppLang entities.
type AppLangGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *AppLangGroupBy) Aggregate(fns ...AggregateFunc) *AppLangGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the group-by query and scans the result into the given value.
func (algb *AppLangGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := algb.path(ctx)
	if err != nil {
		return err
	}
	algb.sql = query
	return algb.sqlScan(ctx, v)
}

func (algb *AppLangGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range algb.fields {
		if !applang.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := algb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (algb *AppLangGroupBy) sqlQuery() *sql.Selector {
	selector := algb.sql.Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(algb.fields)+len(algb.fns))
		for _, f := range algb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(algb.fields...)...)
}

// AppLangSelect is the builder for selecting fields of AppLang entities.
type AppLangSelect struct {
	*AppLangQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (als *AppLangSelect) Scan(ctx context.Context, v interface{}) error {
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	als.sql = als.AppLangQuery.sqlQuery(ctx)
	return als.sqlScan(ctx, v)
}

func (als *AppLangSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := als.sql.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (als *AppLangSelect) Modify(modifiers ...func(s *sql.Selector)) *AppLangSelect {
	als.modifiers = append(als.modifiers, modifiers...)
	return als
}
