// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/lang"
	"github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/predicate"
)

// LangUpdate is the builder for updating Lang entities.
type LangUpdate struct {
	config
	hooks     []Hook
	mutation  *LangMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LangUpdate builder.
func (lu *LangUpdate) Where(ps ...predicate.Lang) *LangUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetCreatedAt sets the "created_at" field.
func (lu *LangUpdate) SetCreatedAt(u uint32) *LangUpdate {
	lu.mutation.ResetCreatedAt()
	lu.mutation.SetCreatedAt(u)
	return lu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lu *LangUpdate) SetNillableCreatedAt(u *uint32) *LangUpdate {
	if u != nil {
		lu.SetCreatedAt(*u)
	}
	return lu
}

// AddCreatedAt adds u to the "created_at" field.
func (lu *LangUpdate) AddCreatedAt(u int32) *LangUpdate {
	lu.mutation.AddCreatedAt(u)
	return lu
}

// SetUpdatedAt sets the "updated_at" field.
func (lu *LangUpdate) SetUpdatedAt(u uint32) *LangUpdate {
	lu.mutation.ResetUpdatedAt()
	lu.mutation.SetUpdatedAt(u)
	return lu
}

// AddUpdatedAt adds u to the "updated_at" field.
func (lu *LangUpdate) AddUpdatedAt(u int32) *LangUpdate {
	lu.mutation.AddUpdatedAt(u)
	return lu
}

// SetDeletedAt sets the "deleted_at" field.
func (lu *LangUpdate) SetDeletedAt(u uint32) *LangUpdate {
	lu.mutation.ResetDeletedAt()
	lu.mutation.SetDeletedAt(u)
	return lu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (lu *LangUpdate) SetNillableDeletedAt(u *uint32) *LangUpdate {
	if u != nil {
		lu.SetDeletedAt(*u)
	}
	return lu
}

// AddDeletedAt adds u to the "deleted_at" field.
func (lu *LangUpdate) AddDeletedAt(u int32) *LangUpdate {
	lu.mutation.AddDeletedAt(u)
	return lu
}

// SetLang sets the "lang" field.
func (lu *LangUpdate) SetLang(s string) *LangUpdate {
	lu.mutation.SetLang(s)
	return lu
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (lu *LangUpdate) SetNillableLang(s *string) *LangUpdate {
	if s != nil {
		lu.SetLang(*s)
	}
	return lu
}

// ClearLang clears the value of the "lang" field.
func (lu *LangUpdate) ClearLang() *LangUpdate {
	lu.mutation.ClearLang()
	return lu
}

// SetLogo sets the "logo" field.
func (lu *LangUpdate) SetLogo(s string) *LangUpdate {
	lu.mutation.SetLogo(s)
	return lu
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (lu *LangUpdate) SetNillableLogo(s *string) *LangUpdate {
	if s != nil {
		lu.SetLogo(*s)
	}
	return lu
}

// ClearLogo clears the value of the "logo" field.
func (lu *LangUpdate) ClearLogo() *LangUpdate {
	lu.mutation.ClearLogo()
	return lu
}

// SetName sets the "name" field.
func (lu *LangUpdate) SetName(s string) *LangUpdate {
	lu.mutation.SetName(s)
	return lu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (lu *LangUpdate) SetNillableName(s *string) *LangUpdate {
	if s != nil {
		lu.SetName(*s)
	}
	return lu
}

// ClearName clears the value of the "name" field.
func (lu *LangUpdate) ClearName() *LangUpdate {
	lu.mutation.ClearName()
	return lu
}

// SetShort sets the "short" field.
func (lu *LangUpdate) SetShort(s string) *LangUpdate {
	lu.mutation.SetShort(s)
	return lu
}

// SetNillableShort sets the "short" field if the given value is not nil.
func (lu *LangUpdate) SetNillableShort(s *string) *LangUpdate {
	if s != nil {
		lu.SetShort(*s)
	}
	return lu
}

// ClearShort clears the value of the "short" field.
func (lu *LangUpdate) ClearShort() *LangUpdate {
	lu.mutation.ClearShort()
	return lu
}

// Mutation returns the LangMutation object of the builder.
func (lu *LangUpdate) Mutation() *LangMutation {
	return lu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LangUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if err := lu.defaults(); err != nil {
		return 0, err
	}
	if len(lu.hooks) == 0 {
		affected, err = lu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LangMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lu.mutation = mutation
			affected, err = lu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lu.hooks) - 1; i >= 0; i-- {
			if lu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LangUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LangUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LangUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lu *LangUpdate) defaults() error {
	if _, ok := lu.mutation.UpdatedAt(); !ok {
		if lang.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized lang.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := lang.UpdateDefaultUpdatedAt()
		lu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lu *LangUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LangUpdate {
	lu.modifiers = append(lu.modifiers, modifiers...)
	return lu
}

func (lu *LangUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lang.Table,
			Columns: lang.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: lang.FieldID,
			},
		},
	}
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldCreatedAt,
		})
	}
	if value, ok := lu.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldCreatedAt,
		})
	}
	if value, ok := lu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldUpdatedAt,
		})
	}
	if value, ok := lu.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldUpdatedAt,
		})
	}
	if value, ok := lu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldDeletedAt,
		})
	}
	if value, ok := lu.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldDeletedAt,
		})
	}
	if value, ok := lu.mutation.Lang(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldLang,
		})
	}
	if lu.mutation.LangCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldLang,
		})
	}
	if value, ok := lu.mutation.Logo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldLogo,
		})
	}
	if lu.mutation.LogoCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldLogo,
		})
	}
	if value, ok := lu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldName,
		})
	}
	if lu.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldName,
		})
	}
	if value, ok := lu.mutation.Short(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldShort,
		})
	}
	if lu.mutation.ShortCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldShort,
		})
	}
	_spec.Modifiers = lu.modifiers
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lang.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// LangUpdateOne is the builder for updating a single Lang entity.
type LangUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LangMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreatedAt sets the "created_at" field.
func (luo *LangUpdateOne) SetCreatedAt(u uint32) *LangUpdateOne {
	luo.mutation.ResetCreatedAt()
	luo.mutation.SetCreatedAt(u)
	return luo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (luo *LangUpdateOne) SetNillableCreatedAt(u *uint32) *LangUpdateOne {
	if u != nil {
		luo.SetCreatedAt(*u)
	}
	return luo
}

// AddCreatedAt adds u to the "created_at" field.
func (luo *LangUpdateOne) AddCreatedAt(u int32) *LangUpdateOne {
	luo.mutation.AddCreatedAt(u)
	return luo
}

// SetUpdatedAt sets the "updated_at" field.
func (luo *LangUpdateOne) SetUpdatedAt(u uint32) *LangUpdateOne {
	luo.mutation.ResetUpdatedAt()
	luo.mutation.SetUpdatedAt(u)
	return luo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (luo *LangUpdateOne) AddUpdatedAt(u int32) *LangUpdateOne {
	luo.mutation.AddUpdatedAt(u)
	return luo
}

// SetDeletedAt sets the "deleted_at" field.
func (luo *LangUpdateOne) SetDeletedAt(u uint32) *LangUpdateOne {
	luo.mutation.ResetDeletedAt()
	luo.mutation.SetDeletedAt(u)
	return luo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (luo *LangUpdateOne) SetNillableDeletedAt(u *uint32) *LangUpdateOne {
	if u != nil {
		luo.SetDeletedAt(*u)
	}
	return luo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (luo *LangUpdateOne) AddDeletedAt(u int32) *LangUpdateOne {
	luo.mutation.AddDeletedAt(u)
	return luo
}

// SetLang sets the "lang" field.
func (luo *LangUpdateOne) SetLang(s string) *LangUpdateOne {
	luo.mutation.SetLang(s)
	return luo
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (luo *LangUpdateOne) SetNillableLang(s *string) *LangUpdateOne {
	if s != nil {
		luo.SetLang(*s)
	}
	return luo
}

// ClearLang clears the value of the "lang" field.
func (luo *LangUpdateOne) ClearLang() *LangUpdateOne {
	luo.mutation.ClearLang()
	return luo
}

// SetLogo sets the "logo" field.
func (luo *LangUpdateOne) SetLogo(s string) *LangUpdateOne {
	luo.mutation.SetLogo(s)
	return luo
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (luo *LangUpdateOne) SetNillableLogo(s *string) *LangUpdateOne {
	if s != nil {
		luo.SetLogo(*s)
	}
	return luo
}

// ClearLogo clears the value of the "logo" field.
func (luo *LangUpdateOne) ClearLogo() *LangUpdateOne {
	luo.mutation.ClearLogo()
	return luo
}

// SetName sets the "name" field.
func (luo *LangUpdateOne) SetName(s string) *LangUpdateOne {
	luo.mutation.SetName(s)
	return luo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (luo *LangUpdateOne) SetNillableName(s *string) *LangUpdateOne {
	if s != nil {
		luo.SetName(*s)
	}
	return luo
}

// ClearName clears the value of the "name" field.
func (luo *LangUpdateOne) ClearName() *LangUpdateOne {
	luo.mutation.ClearName()
	return luo
}

// SetShort sets the "short" field.
func (luo *LangUpdateOne) SetShort(s string) *LangUpdateOne {
	luo.mutation.SetShort(s)
	return luo
}

// SetNillableShort sets the "short" field if the given value is not nil.
func (luo *LangUpdateOne) SetNillableShort(s *string) *LangUpdateOne {
	if s != nil {
		luo.SetShort(*s)
	}
	return luo
}

// ClearShort clears the value of the "short" field.
func (luo *LangUpdateOne) ClearShort() *LangUpdateOne {
	luo.mutation.ClearShort()
	return luo
}

// Mutation returns the LangMutation object of the builder.
func (luo *LangUpdateOne) Mutation() *LangMutation {
	return luo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LangUpdateOne) Select(field string, fields ...string) *LangUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Lang entity.
func (luo *LangUpdateOne) Save(ctx context.Context) (*Lang, error) {
	var (
		err  error
		node *Lang
	)
	if err := luo.defaults(); err != nil {
		return nil, err
	}
	if len(luo.hooks) == 0 {
		node, err = luo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LangMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			luo.mutation = mutation
			node, err = luo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(luo.hooks) - 1; i >= 0; i-- {
			if luo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = luo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, luo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Lang)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from LangMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LangUpdateOne) SaveX(ctx context.Context) *Lang {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LangUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LangUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (luo *LangUpdateOne) defaults() error {
	if _, ok := luo.mutation.UpdatedAt(); !ok {
		if lang.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized lang.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := lang.UpdateDefaultUpdatedAt()
		luo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (luo *LangUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LangUpdateOne {
	luo.modifiers = append(luo.modifiers, modifiers...)
	return luo
}

func (luo *LangUpdateOne) sqlSave(ctx context.Context) (_node *Lang, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lang.Table,
			Columns: lang.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: lang.FieldID,
			},
		},
	}
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Lang.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lang.FieldID)
		for _, f := range fields {
			if !lang.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lang.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldCreatedAt,
		})
	}
	if value, ok := luo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldCreatedAt,
		})
	}
	if value, ok := luo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldUpdatedAt,
		})
	}
	if value, ok := luo.mutation.AddedUpdatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldUpdatedAt,
		})
	}
	if value, ok := luo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldDeletedAt,
		})
	}
	if value, ok := luo.mutation.AddedDeletedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: lang.FieldDeletedAt,
		})
	}
	if value, ok := luo.mutation.Lang(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldLang,
		})
	}
	if luo.mutation.LangCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldLang,
		})
	}
	if value, ok := luo.mutation.Logo(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldLogo,
		})
	}
	if luo.mutation.LogoCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldLogo,
		})
	}
	if value, ok := luo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldName,
		})
	}
	if luo.mutation.NameCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldName,
		})
	}
	if value, ok := luo.mutation.Short(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: lang.FieldShort,
		})
	}
	if luo.mutation.ShortCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: lang.FieldShort,
		})
	}
	_spec.Modifiers = luo.modifiers
	_node = &Lang{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lang.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
