// Code generated by ent, DO NOT EDIT.

package country

import (
	"entgo.io/ent"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the country type in the database.
	Label = "country"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldEntID holds the string denoting the ent_id field in the database.
	FieldEntID = "ent_id"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldFlag holds the string denoting the flag field in the database.
	FieldFlag = "flag"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldShort holds the string denoting the short field in the database.
	FieldShort = "short"
	// Table holds the table name of the country in the database.
	Table = "countries"
)

// Columns holds all SQL columns for country fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldEntID,
	FieldCountry,
	FieldFlag,
	FieldCode,
	FieldShort,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultEntID holds the default value on creation for the "ent_id" field.
	DefaultEntID func() uuid.UUID
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DefaultFlag holds the default value on creation for the "flag" field.
	DefaultFlag string
	// DefaultCode holds the default value on creation for the "code" field.
	DefaultCode string
	// DefaultShort holds the default value on creation for the "short" field.
	DefaultShort string
)
