// Code generated by ent, DO NOT EDIT.

package lang

import (
	"entgo.io/ent"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the lang type in the database.
	Label = "lang"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldLang holds the string denoting the lang field in the database.
	FieldLang = "lang"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldShort holds the string denoting the short field in the database.
	FieldShort = "short"
	// Table holds the table name of the lang in the database.
	Table = "langs"
)

// Columns holds all SQL columns for lang fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldLang,
	FieldLogo,
	FieldName,
	FieldShort,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/g11n-middleware/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultLang holds the default value on creation for the "lang" field.
	DefaultLang string
	// DefaultLogo holds the default value on creation for the "logo" field.
	DefaultLogo string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultShort holds the default value on creation for the "short" field.
	DefaultShort string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
